# Generated by Django 4.0.2 on 2022-02-09 22:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github', models.URLField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True, max_length=150)),
                ('img_url', models.URLField(blank=True, max_length=150)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=35), size=None)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_category', models.ManyToManyField(to='programmingProjects.ProjectCategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
